version: "3"
services:
  node:
    image: "cyborg/node14"
    container_name: cyborg-web-build
    user: "root"
    working_dir: /web
    volumes:
      - ../:/web
    command: >
      /bin/bash -c "
      cd app;
      npm run build;
      "
