export const get_id = (id, other_id, another_id) => {
  return {
    svg: 'BASE-SVG',
    g: 'BASE-G',
    path_g: 'NEW-PATH-G',
    bbox: 'BASE-SVG-BBOX',
    g_topview: 'G-TOPVIEW',
    active_bbox: 'ACTIVE-NAVIGATOR-BBOX',
    storage_bbox_sid: `STORAGE-BBOX-${id}`,
    storage_bbox_sid_sgid_rid: `STORAGE-SGROUP-REGION-BBOX-${id}-${other_id}-${another_id}`,
    storage_bbox_sid_rid: `STORAGE-REGION-BBOX-${id}-${other_id}`,
    newnode_rid: `NEWNODE-REGION-${id}`,
    newnode_mode_id: `NEWNODE-${id}-${other_id}`,
    storage_img_sid: `STORAGE-IMG-${id}`,
    assist_g: 'ASSIST-G',
    assist_node: `ASSIST-NODE-${id}`,
    g_type_id: `G-${id}-${other_id}`,
    assist_box: 'ASSIST-BOX',
    polygon_box: 'POLYGON-BOX',
    assist_input: 'ASSIST-INPUT',
    polygon_input: 'POLYGON-INPUT',
    temp_text: 'TEMP-SIZE-TEXT',
    assist_line_g: 'ASSIST-LINE-G',
    arrow: `ARROW-${id}-${other_id}`,
    newnode_group_g: `NEWNODE-GROUP-${id}-G`,
    newnode_item_g: `NEWNODE-ITEM-${id}-G`,
    polygon_item: `POLYGON-ITEM-${id}`,
    polygon_g: `POLYGON-G`,
    the_polygon: `THE-POLYGON`,
    tools_g: `TOOLS-G`,
    tools_item: `TOOLS-ITEM-${id}`,
    model: 'MODEL-G',
    model_svg: `MODEL-SVG-${id}`,
    line: `LINE-${id}`,
    line_text: `${id}-TEXT`,
  };
};

export const get_class = (id, other_id) => {
  return {
    svg: 'sc-base-svg',
    bbox: 'cad-bbox-rect bg-dark',
    topview: 'cad-layer-line',
    topview_sid: `storage-topview-${id}`,
    topview_sid_rid: `storage-topview-${id}-${other_id}`,
    // storage_img: 'storage-img graph-storage-img',
    storage_img: 'graph-storage-img',
    newnode: 'newnode',
    cad_draw_polygon: `cad-polygon-${id}`,
    region: 'cad-polygon-region',
    active_bbox: 'active-bbox-rect',
    storage_region: 'storage-bbox-region',
    storage_region_sid: `storage-bbox-region-${id}`,
    storage_sgroup_sgid: `storage-bbox-sgroup-${id}`,
    storage_region_sid_rid: `storage-bbox-region-${id}-${other_id}`,
    storage_region_active: 'storage-bbox-region-active',
    assist_node: 'assist-node',
    assist_node_id: `assist-node-${id}`,
    has_assist: 'has-assist',
    arrow: `arrow-${id}`,
    newnode_group_class: 'newnode-group-class',
    newnode_item_class: 'newnode-item-class',
    g_layer: `g-${id}`,
    model_svg: 'svg-model',
    customizable: id ? 'customizable' : 'uncustomizable',
    line: 'line',
    click_through: 'click-through',
  };
};
